const enum UserErrors {
	DB_USER_NOT_FOUND = "DB_USER_NOT_FOUND",
	MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND",
	WRONG_ID = "WRONG_ID",
	WRONG_HEX = "WRONG_HEX",
	MISSING_PERMISSIONS = "MISSING_PERMISSIONS",
	API_UNAVAILABLE = "API_UNAVAILABLE",
	CLOSED_DM = "CLOSED_DM",
	SPECIFIED_MESSAGE_NOT_FOUND = "SPECIFIED_MESSAGE_NOT_FOUND",
	CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND",

	// Raid related error codes
	RAID_TIME_ERROR = "RAID_TIME_ERROR",
	RAID_GUIDE_NOT_FOUND = "RAID_GUIDE_NOT_FOUND",
	RAID_NOT_FOUND = "RAID_NOT_FOUND",
	RAID_MISSING_DATA_FOR_CLEARS = "RAID_MISSING_DATA_FOR_CLEARS",
	RAID_NOT_ENOUGH_CLEARS = "RAID_NOT_ENOUGH_CLEARS",
	RAID_ALREADY_JOINED = "RAID_ALREADY_JOINED",

	// LFG related error codes
	LFG_ACTIVITY_NOT_FOUND = "LFG_ACTIVITY_NOT_FOUND",
	LFG_NOT_FOUND = "LFG_NOT_FOUND",
	LFG_MESSAGE_NOT_FOUND = "LFG_MESSAGE_NOT_FOUND",
	LFG_ALREADY_JOINED = "LFG_ALREADY_JOINED",
	LFG_MISSING_DLC_TO_CREATE_LFG = "LFG_MISSING_DLC_TO_CREATE_LFG",
	LFG_SPECIFY_LFG = "LFG_SPECIFY_LFG",
	LFG_NOT_AVAILABLE_LFGS_TO_EDIT = "LFG_NOT_AVAILABLE_LFGS_TO_EDIT",
	LFG_CANNOT_ADD_BOT = "LFG_CANNOT_ADD_BOT",

	// LFG and Raid related error codes
	ACTIVITY_MISSING_PERMISSIONS = "ACTIVITY_MISSING_PERMISSIONS",
	ACTIVITY_MISSING_DLC = "ACTIVITY_MISSING_DLC",
}

export default UserErrors;
